### ISSUE TITLE
Doesn't work on Universal setup with Webpack?

### ISSUE THREAD

**Issue by Ganasist** [bryaneaton13/react-pull-to-refresh#13]
I'm getting this error after install:

```
/node_modules/hammerjs/hammer.js:2643
[0] })(window, document, 'Hammer');
[0]    ^
[0]
[0] ReferenceError: window is not defined
```

**Comment by bryaneaton13** [comment]
Check out this issue https://github.com/bryaneaton13/react-pull-to-refresh/issues/7
Hammerjs doesn't support server-side rendering as of right now. Once it does, it can be updated.
