### ISSUE TITLE
Cannot resolve module 'react-pull-to-refresh'...

### ISSUE THREAD

**Issue by shangboyang** [bryaneaton13/react-pull-to-refresh#17]
Hi，

When I run 'webpack' I keep getting a "Module not found: Error: Cannot resolve module 'react-pull-to-refresh'"
How to import this module?
Thx~~~

My 'node' version is '8.1.13' , 'npm' version is '5.0.3'.

**Comment by bryaneaton13** [comment]
Can you give any more details please or a repo to reproduce the issue?
I just ran my example with the latest version of this module pulled from npm and it doesn't give me any issues.
Make sure you did `npm install react-pull-to-refresh --save` and you're importing it properly `import ReactPullToRefresh from 'react-pull-to-refresh';`
I haven't tried it with those versions of node and npm, so it could be a problem with that.
You could also try going back to an older version to see if that works, I could have messed something up when I changed the peerdependencies recently
`npm i react-pull-to-refresh@1.0.6 -S`
