### ISSUE TITLE
Target specific component?

### ISSUE THREAD

**Issue by sami616** [bryaneaton13/react-pull-to-refresh#18]
Is it possible to somehow wrap all my main body content in the pull-to-refresh component but specify only a specific component inside to trigger the pull? So, only when pandown is detected on the header component for example?

**Comment by hequanb** [comment]
+1, I got this issue too

**Comment by arivanbastos** [comment]
+1

**Comment by bryaneaton13** [comment]
I don't have a specific example, but it may be possible if you try enabling/disabling the ReactPullToRefresh at the times when you want it to be draggable.

Something like:
```ts
<ReactPullToRefresh disabled={!enablePullToRefresh} ...>
  <div
    onMouseEnter={() => setEnablePullToRefresh(true)}
    onMouseLeave={() => setEnablePullToRefresh(false)}
  >
    Header
  </div>
  <div>Other Content</div>
</ReactPullToRefresh
```
