### ISSUE TITLE
Infinite scrolling integration

### ISSUE THREAD

**Issue by Volodymyr128** [bryaneaton13/react-pull-to-refresh#2]
I need component which has both: pull-to-refresh and load-more on scroll down. 
How to add infinite scrolling to your component?

**Comment by bryaneaton13** [comment]
You can put all of your own code inside the children of the PullToRefresh component and handle it all like you would with any InfiniteScroll component. Then the entire area where the items are rendered would be a pullable area.

Example:

``` xml
<ReactPullToRefresh ...props>
  <InfScroll ...InfScrollprops>
    {items}
  </InfScroll>
</ReactPullToRefresh>
```
