### ISSUE TITLE
Need a props to control animate speed

### ISSUE THREAD

**Issue by DaveNguyenHuy** [bryaneaton13/react-pull-to-refresh#22]
As the title, Its better to add a new props that allow us to control the speed for smooth scroll up animation, thanks

**Comment by bryaneaton13** [comment]
I'm not sure what animate speed you are talking about. Is it the transition in the `.css` file? You can change that to be whatever you need it as.
If you think it should be something else, feel free to put in a PR and I'll take a look at it.
