### ISSUE TITLE
Can you provide an example for how this would be used in importing applications?

### ISSUE THREAD

**Issue by EricWehrly** [bryaneaton13/react-pull-to-refresh#28]
https://github.com/bryaneaton13/react-pull-to-refresh/blob/bde6d7963e650272cf8a0c11820f43e88ad3d196/examples/basic/app.js#L3

**Comment by bryaneaton13** [comment]
You would import it from the package like other npm packages. No need to navigate anywhere.
```
import ReactPullToRefresh from 'react-pull-to-refresh';
```

The example isn't importing the package from `node_modules`, it is importing from a static directory.
