### ISSUE TITLE
Definitly Typed Version

### ISSUE THREAD

**Issue by vanhoutenbos** [bryaneaton13/react-pull-to-refresh#29]
Hi,

Is it possible for you to add a DefinitlyTyped version so that I can use the library in my typescript applications?

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by DanielRuf** [comment]
This project does not seem to be actively maintained. The last commit was about 2 years ago and the last tagged release about 4 years ago.

**Comment by vanhoutenbos** [comment]
> This project does not seem to be actively maintained. The last commit was about 2 years ago and the last tagged release about 4 years ago.

Unfortunatly it seems that way with all pull to release projects for reactjs

**Comment by DanielRuf** [comment]
There is https://github.com/BoxFactura/pulltorefresh.js which works perfectly in React projects and is still actively maintained.

**Comment by bryaneaton13** [comment]
The latest version of this package now uses Typescript so there's no need for a DefinitelyTyped version as the types are now included.
