### ISSUE TITLE
Pulling down again during the pull-down loading will cause the loading prompt to be retracted

### ISSUE THREAD

**Issue by ZWBruce** [bryaneaton13/react-pull-to-refresh#31]
The official demo can be reproduced：
[Pulling down again during the pull-down loading will cause the loading prompt to be retracted](http://react-component.github.io/m-pull-to-refresh/examples/base.html)

**Comment by bryaneaton13** [comment]
Thanks for opening this issue! The page that you linked goes to another GitHub repo https://github.com/react-component/m-pull-to-refresh

I checked the code from this repository and it does not seem to do what you mentioned (see gif below).

![Screen Recording 2023-03-22 at 9 54 18 AM](https://user-images.githubusercontent.com/10492768/226928344-86e50d01-c5df-407e-8dcd-2c3909613fd6.gif)
