### ISSUE TITLE
how to pull up to load more with this component

### ISSUE THREAD

**Issue by batulu12** [bryaneaton13/react-pull-to-refresh#5]

**Comment by bryaneaton13** [comment]
That is a limitation of the [web-pull-to-refresh](https://github.com/apeatling/web-pull-to-refresh) library that is being used.
Feel free to submit a PR to that or the [wptr.1.1.js](https://github.com/bryaneaton13/react-pull-to-refresh/blob/master/src/pull-to-refresh/wptr.1.1.js) file to support a negative `distance` in the `_panUp` function.

**Comment by gotoAndBliss** [comment]
It seems that this is by default working. Latest installation causes a refresh regardless of pan direction.
