### ISSUE TITLE
Customize loadingIcons

### ISSUE THREAD

**Issue by andrzey** [bryaneaton13/react-pull-to-refresh#6]
What exactly are the loading and icon props doing? Is loading the arrow up and icon the arrow down? And is there a prop available so I can customize the loading animation that should appear?

**Comment by bryaneaton13** [comment]
The `loading` prop is the loading animation (the 3 dots that appear while waiting). You'll want to apply a hiding/showing style onto the prop based on the classes applied to the body https://github.com/bryaneaton13/react-pull-to-refresh/blob/master/examples/basic/app.css#L47
You can use a completely custom icon for this, just apply the proper classes to hide/show it at the right time.

The `icon` prop is just a single element that you'll want to apply some transitions to whenever certain classes get put on the body of the page. Check out https://github.com/bryaneaton13/react-pull-to-refresh/blob/master/examples/basic/app.css#L31 to see the transformation that gets applied to the `icon` element whenever the user is pulling down the page far enough to cause a refresh. That icon is also being hidden whenever the page is `loading` or being `reset`.

I hope this helps!
