### ISSUE TITLE
server side rendering error

### ISSUE THREAD

**Issue by yloeza** [bryaneaton13/react-pull-to-refresh#7]
When I'm trying to render on the server I'm getting an error on hammer.js that window is not defined.

`ReferenceError: window is not defined
   at Object.<anonymous> (/my-project/node_modules/react-pull-to-refresh/node_modules/hammerjs/hammer.js:2643:4)`

It would be nice we can support server side rendering, as a workaround I will need to check if window is defined before I require `react-pull-to-refresh`

```
var PullToRefresh
if (global.window) {
  PullToRefresh = require('react-pull-to-refresh')
}
```

**Comment by bryaneaton13** [comment]
There is an open issue in hammer.js about that. Once it is resolved and pushed out to a new version, I can upgrade the dependency on it. Or you could send a PR once it's updated.
https://github.com/hammerjs/hammer.js/issues/930
