### ISSUE TITLE
cannot build with command 

### ISSUE THREAD

**Issue by liz282907** [bryaneaton13/react-pull-to-refresh#9]
i clone the project and npm install all the dependencies,and try to build to get the dist package with"npm run prepublish",however, there is sth wrong with the command of build:file and minify,.

**Comment by bryaneaton13** [comment]
Please make sure that npm installed properly and all dependencies (including dev-dependencies) installed correctly.
If that doesn't work, try updating your version of node.
In the future, please supply some more information about the error you are getting. It will help isolate the problem further.
Thanks!
